<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.6.2" />
		<PackageReference Include="MSTest.TestFramework" Version="3.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Backend_PlanoriaCapstone\Backend_PlanoriaCapstone.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="AuthTests\" />
	  <Folder Include="FlashcardTests\" />
	  <Folder Include="IntegrationsTests\" />
	  <Folder Include="ProgresoTests\" />
	  <Folder Include="QuizTests\" />
	</ItemGroup>

</Project>